import pandas as pd
from zk import ZK
import requests
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import calendar
from datetime import datetime, timedelta
import os
import json
import sys
from pathlib import Path
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import io
import tempfile

BASE_DIR = Path(__file__).resolve().parent

LOGO_PATH = Path(os.getenv("LOGO_PATH", str(BASE_DIR / "company_logo.png")))
if not LOGO_PATH.is_absolute():
    LOGO_PATH = (BASE_DIR / LOGO_PATH).resolve()

FOOTER_TEXT = (
    "Office - 5, 1st Floor, Markaz Al-Mahbooba, Prince Abdul Mohsen Bin Aziz Road, "
    "Madinah Munawarah, Kingdom of Saudi Arabia. This report is generated by IICC IT dept. "
    "with AI Attendance Agent bot V 1.0"
)

# Load variables from .env
load_dotenv(BASE_DIR / ".env")

# Access them like this:
erp_url = os.getenv("ERP_URL")
api_key = os.getenv("ERP_API_KEY")
email_pass = os.getenv("EMAIL_PASS")

print(f"Connecting to ERP at: {erp_url}")


def ensure_log_file_exists():
    log_dir = BASE_DIR / Path(os.getenv("LOG_DIR", "logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / os.getenv("LOG_FILE", "attendance_ids.log")
    if not log_path.exists():
        with log_path.open("w", encoding="utf-8") as f:
            f.write(f"Attendance ID log created: {datetime.now().isoformat()}\n")
    return log_path

ensure_log_file_exists()


def should_send_report(now=None):
    if now is None:
        now = datetime.now()
    if os.getenv("FORCE_SEND", "0") == "1":
        return True
    if now.hour != 11:
        return False
    return now.weekday() == 4 or now.day == 1


def add_page_header(pdf, month_name, page_title):
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "B", 14)
    pdf.set_line_width(0.18)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_y(10)
    if LOGO_PATH.is_file():
        pdf.image(str(LOGO_PATH), x=10, y=10, w=25)
    pdf.set_x(0)
    pdf.cell(0, 6, "Insight International Contracting Company", ln=1, align='C')
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 6, page_title, ln=1, align='C')
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 5, f"Month: {month_name}", ln=1, align='C')
    pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  |  Page {pdf.page_no()}", ln=1, align='C')
    pdf.ln(2)
    pdf.line(10, pdf.get_y(), pdf.w - 10, pdf.get_y())
    pdf.ln(3)


def add_page_footer(pdf):
    pdf.set_line_width(0.18)
    pdf.set_draw_color(192, 0, 0)
    footer_y = pdf.h - 15
    pdf.line(10, footer_y, pdf.w - 10, footer_y)
    pdf.set_xy(10, footer_y + 2)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(192, 0, 0)
    pdf.cell(0, 4, FOOTER_TEXT, 0, 1, 'C')
    pdf.set_text_color(0, 0, 0)

# 1. Fetch Biometric Data
def get_biometric_data():
    # Calculate previous month for data filtering
    now = datetime.now()
    if now.month == 1:
        prev_month = 12
        prev_year = now.year - 1
    else:
        prev_month = now.month - 1
        prev_year = now.year
    
    # Get first and last day of previous month
    month_start = datetime(prev_year, prev_month, 1)
    month_end = datetime(prev_year, prev_month, calendar.monthrange(prev_year, prev_month)[1], 23, 59, 59)
    
    zk = ZK('192.168.8.4', port=4370, timeout=5)
    conn = zk.connect()
    attendance = conn.get_attendance()
    # Filter for previous month
    filtered_attendance = [{'user_id': record.user_id, 'timestamp': record.timestamp} for record in attendance if month_start <= record.timestamp <= month_end]
    df_biometric = pd.DataFrame(filtered_attendance)
    conn.disconnect()
    return df_biometric

# 2. Fetch ERP User Info
def get_erp_users():
    url = erp_url + '/api/resource/Employee'
    headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}'}
    params = {
        'fields': '["employee_name", "attendance_device_id", "department", "designation"]',
        'limit_page_length': 1000
    }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()['data']
        return pd.DataFrame(data)
    else:
        raise Exception(f"ERP API Error: {response.status_code} - {response.text}")


def get_remote_checkin_data():
    remote_source = os.getenv("REMOTE_CHECKIN_SOURCE")
    if not remote_source:
        return pd.DataFrame(columns=['user_id', 'timestamp'])

    try:
        if remote_source.lower().startswith("http"):
            headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}' }
            response = requests.get(remote_source, headers=headers, timeout=10)
            response.raise_for_status()
            payload = response.json()
            data = payload.get('data', payload) if isinstance(payload, dict) else payload
            df = pd.DataFrame(data)
        elif remote_source.lower().endswith('.csv'):
            df = pd.read_csv(remote_source)
        elif remote_source.lower().endswith('.json'):
            df = pd.read_json(remote_source)
        else:
            raise ValueError("Unsupported REMOTE_CHECKIN_SOURCE format. Use HTTP, CSV, or JSON.")

        user_field = os.getenv('REMOTE_CHECKIN_USER_FIELD')
        if user_field and user_field in df.columns:
            df = df.rename(columns={user_field: 'user_id'})
        elif 'attendance_device_id' in df.columns:
            df = df.rename(columns={'attendance_device_id': 'user_id'})
        elif 'employee_id' in df.columns:
            df = df.rename(columns={'employee_id': 'user_id'})

        if 'timestamp' not in df.columns:
            raise ValueError("Remote checkin source must include a 'timestamp' column")

        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        df = df.dropna(subset=['user_id', 'timestamp'])
        df['user_id'] = df['user_id'].astype(str)
        return df[['user_id', 'timestamp']]
    except Exception as exc:
        print(f"Warning: failed to load remote checkins from {remote_source}: {exc}")
        return pd.DataFrame(columns=['user_id', 'timestamp'])


def write_id_log(df_bio, df_users, df_remote):
    log_dir = BASE_DIR / Path(os.getenv("LOG_DIR", "logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / os.getenv("LOG_FILE", "attendance_ids.log")

    bio_ids = sorted(set(df_bio['user_id'].astype(str).unique()))
    # Filter out NaN values and convert to string
    erp_ids = sorted(set(str(id) for id in df_users['attendance_device_id'].dropna().unique()))
    remote_ids = sorted(set(df_remote['user_id'].astype(str).unique())) if not df_remote.empty else []

    matched_ids = sorted(set(bio_ids).intersection(erp_ids))
    biometric_only = sorted(set(bio_ids) - set(erp_ids))
    erp_only = sorted(set(erp_ids) - set(bio_ids))

    with open(log_path, 'a', encoding='utf-8') as log_file:
        log_file.write(f"\n===== Attendance ID Log: {datetime.now().isoformat()} =====\n")
        log_file.write(f"Biometric IDs ({len(bio_ids)}): {bio_ids}\n")
        log_file.write(f"ERP IDs ({len(erp_ids)}): {erp_ids}\n")
        if remote_ids:
            log_file.write(f"Remote check-in IDs ({len(remote_ids)}): {remote_ids}\n")
            remote_matched = sorted(set(remote_ids).intersection(erp_ids))
            remote_only = sorted(set(remote_ids) - set(erp_ids))
            log_file.write(f"Remote matched ERP IDs ({len(remote_matched)}): {remote_matched}\n")
            log_file.write(f"Remote-only IDs ({len(remote_only)}): {remote_only}\n")

        log_file.write(f"Matched IDs ({len(matched_ids)}): {matched_ids}\n")
        log_file.write(f"Biometric-only IDs ({len(biometric_only)}): {biometric_only}\n")
        log_file.write(f"ERP-only IDs ({len(erp_only)}): {erp_only}\n")
        log_file.write("====================================================\n")

    print(f"Attendance ID log written to: {log_path}")

# 3. Generate PDF Summary
# 3. Generate PDF Summary
def create_pdf(df_final, filename, month_name, df_merged):
    pdf = FPDF('L', 'mm', 'A4')
    pdf.set_auto_page_break(auto=False, margin=0)
    pdf.add_page()
    add_page_header(pdf, month_name, f"Monthly Attendance Summary - {month_name}")

    table_width = 255
    page_width = pdf.w
    left_margin = (page_width - table_width) / 2
    pdf.set_line_width(0.18)
    pdf.set_draw_color(192, 0, 0)

    headers = [
        ("No.", 12),
        ("Employee Name", 64),
        ("Designation", 60),
        ("Department", 60),
        ("Hours", 30),
        ("Pct", 29),
    ]
    row_height = 16
    table_y = pdf.get_y()
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(192, 0, 0)
    pdf.set_text_color(255, 255, 255)
    x = left_margin
    for label, width in headers:
        pdf.set_xy(x, table_y)
        pdf.cell(width, row_height, label, 1, 0, 'C', fill=True)
        x += width

    pdf.set_y(table_y + row_height)
    pdf.set_font("Arial", "", 9)
    pdf.set_text_color(0, 0, 0)

    for index, row in df_final.iterrows():
        row_y = pdf.get_y()
        if row_y + row_height > pdf.h - 20:
            add_page_footer(pdf)
            pdf.add_page()
            add_page_header(pdf, month_name, f"Monthly Attendance Summary - {month_name}")
            table_y = pdf.get_y()
            pdf.set_font("Arial", "B", 10)
            pdf.set_fill_color(192, 0, 0)
            pdf.set_text_color(255, 255, 255)
            x = left_margin
            for label, width in headers:
                pdf.set_xy(x, table_y)
                pdf.cell(width, row_height, label, 1, 0, 'C', fill=True)
                x += width
            pdf.set_y(table_y + row_height)
            pdf.set_font("Arial", "", 9)
            pdf.set_text_color(0, 0, 0)
            row_y = pdf.get_y()

        x = left_margin
        pdf.set_xy(x, row_y)
        pdf.cell(12, row_height, str(row['serial_no']), 1, 0, 'C')
        x += 12
        pdf.set_xy(x, row_y)
        pdf.cell(64, row_height, str(row['employee_name']), 1, 0)
        x += 64
        pdf.set_xy(x, row_y)
        pdf.cell(60, row_height, str(row['designation']), 1, 0)
        x += 60
        pdf.set_xy(x, row_y)
        pdf.cell(60, row_height, str(row.get('department', 'N/A')), 1, 0)
        x += 60
        pdf.set_xy(x, row_y)
        pdf.cell(30, row_height, f"{row['total_hours']:.1f}", 1, 0, 'C')
        x += 30

        pct_val = max(0, min(row['percentage'], 100))
        pct_display = f"{pct_val:.1f}%"
        fig, ax = plt.subplots(figsize=(0.45, 0.45))
        ax.pie([pct_val, 100 - pct_val], colors=['#C00000', '#FFFFFF'], startangle=90, counterclock=False, wedgeprops={'linewidth': 0})
        ax.axis('equal')
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as temp_img:
            fig.savefig(temp_img.name, format='png', transparent=True, bbox_inches='tight')
        plt.close(fig)
        image_y = row_y + 3
        pdf.image(temp_img.name, x=x + 8, y=image_y, w=9, type='PNG')
        try:
            os.remove(temp_img.name)
        except OSError:
            pass

        pdf.set_xy(x, row_y)
        pdf.cell(29, row_height, pct_display, 1, 0, 'C')
        pdf.set_y(row_y + row_height)

    add_page_footer(pdf)
    add_timesheet_pages(pdf, df_final, df_merged, month_name)
    pdf.output(filename)

def add_timesheet_pages(pdf, df_final, df_merged, month_name):
    for index, row in df_final.iterrows():
        emp_name = row['employee_name']
        emp_device_id = str(row.get('attendance_device_id', ''))
        
        emp_data = df_merged[df_merged['attendance_device_id'] == emp_device_id].copy()
        if emp_data.empty:
            continue
        
        emp_data['date'] = emp_data['timestamp'].dt.date
        emp_data['time'] = emp_data['timestamp'].dt.strftime('%H:%M:%S')
        emp_data = emp_data.sort_values('timestamp')
        
        def draw_timesheet_header():
            pdf.set_font("Arial", "B", 9)
            pdf.set_fill_color(192, 0, 0)
            pdf.set_text_color(255, 255, 255)
            pdf.set_x(left_margin)
            pdf.cell(15, 8, "S.No", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Date", 1, 0, 'C', fill=True)
            pdf.cell(25, 8, "Day", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Check-In", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Check-Out", 1, 0, 'C', fill=True)
            pdf.cell(25, 8, "Duration", 1, 1, 'C', fill=True)
            pdf.set_font("Arial", "", 8)
            pdf.set_text_color(0, 0, 0)

        pdf.add_page('P')
        add_page_header(pdf, month_name, f"Attendance Timesheet - {emp_name}")
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 6, f"Designation: {row.get('designation', 'N/A')} | Department: {row.get('department', 'N/A')}", ln=1, align='C')
        pdf.ln(4)

        table_width = 155
        page_width = pdf.w
        left_margin = (page_width - table_width) / 2
        pdf.set_x(left_margin)
        pdf.set_line_width(0.18)

        draw_timesheet_header()

        try:
            month_num = datetime.strptime(month_name.split()[0], '%B').month
            year = int(month_name.split()[1])
        except Exception:
            month_num = 1
            year = 2026
        month_start = datetime(year, month_num, 1).date()
        month_end = datetime(year, month_num, calendar.monthrange(year, month_num)[1]).date()
        all_dates = [month_start + timedelta(days=i) for i in range((month_end - month_start).days + 1)]
        
        serial_no = 1
        total_days = 0
        total_hours = 0
        for date_val in all_dates:
            if pdf.get_y() + 12 > pdf.h - 20:
                add_page_footer(pdf)
                pdf.add_page('P')
                add_page_header(pdf, month_name, f"Attendance Timesheet - {emp_name}")
                pdf.set_font("Arial", "", 10)
                pdf.cell(0, 6, f"Designation: {row.get('designation', 'N/A')} | Department: {row.get('department', 'N/A')}", ln=1, align='C')
                pdf.ln(4)
                pdf.set_x(left_margin)
                pdf.set_line_width(0.18)
                draw_timesheet_header()

            day_data = emp_data[emp_data['date'] == date_val].sort_values('timestamp')
            day_name = date_val.strftime('%A')
            if len(day_data) >= 2:
                check_in = day_data.iloc[0]['time']
                check_out = day_data.iloc[-1]['time']
                duration_min = (day_data.iloc[-1]['timestamp'] - day_data.iloc[0]['timestamp']).total_seconds() / 60
                duration_hrs = f"{int(duration_min // 60)}:{int(duration_min % 60):02d}"
                total_days += 1
                total_hours += duration_min / 60
            elif len(day_data) == 1:
                check_in = day_data.iloc[0]['time']
                check_out = "N/A"
                duration_hrs = "N/A"
            else:
                check_in = "N/A"
                check_out = "N/A"
                duration_hrs = "N/A"
            
            pdf.set_x(left_margin)
            pdf.cell(15, 6, str(serial_no), 1, 0, 'C')
            pdf.cell(30, 6, str(date_val), 1, 0, 'C')
            pdf.cell(25, 6, day_name[:3], 1, 0, 'C')  # Short day name
            pdf.cell(30, 6, str(check_in), 1, 0, 'C')
            pdf.cell(30, 6, str(check_out), 1, 0, 'C')
            pdf.cell(25, 6, duration_hrs, 1, 1, 'C')
            serial_no += 1
        
        summary = f"Total Days: {total_days}, Total Hours: {total_hours:.1f}"
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 6, summary, 0, 1, 'C')
        add_page_footer(pdf)

# 4. Email Function
def send_email(filename, month_name):
    msg = MIMEMultipart()
    msg['Subject'] = f'Monthly Attendance Report - {month_name}'
    msg['From'] = os.getenv("EMAIL_USER")
    msg['To'] = os.getenv("RECIPIENT_EMAIL")
    
    with open(filename, "rb") as f:
        attach = MIMEApplication(f.read(), _subtype="pdf")
        attach.add_header('Content-Disposition', 'attachment', filename=Path(filename).name)
        msg.attach(attach)
    
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = int(os.getenv("SMTP_PORT"))
    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_USER"), email_pass)
        server.send_message(msg)


def send_whatsapp(filename, month_name):
    to_number = os.getenv("WHATSAPP_TO_NUMBER")
    from_number = os.getenv("WHATSAPP_FROM_NUMBER")
    if not to_number or not from_number:
        print("WhatsApp not configured; skipping WhatsApp notification.")
        return

    message_template = os.getenv(
        "WHATSAPP_MESSAGE_TEMPLATE",
        f"Attendance report for {month_name} is ready. Please check your email or download from the provided link."
    )
    message = message_template.replace("{month_name}", month_name).replace("{filename}", Path(filename).name)

    twilio_sid = os.getenv("TWILIO_ACCOUNT_SID")
    twilio_token = os.getenv("TWILIO_AUTH_TOKEN")
    media_base = os.getenv("WHATSAPP_MEDIA_URL_BASE")

    if twilio_sid and twilio_token:
        url = f"https://api.twilio.com/2010-04-01/Accounts/{twilio_sid}/Messages.json"
        data = {
            "From": f"whatsapp:{from_number}",
            "To": f"whatsapp:{to_number}",
            "Body": message,
        }
        if media_base:
            data["MediaUrl"] = media_base.rstrip("/") + "/" + Path(filename).name
        response = requests.post(url, data=data, auth=(twilio_sid, twilio_token), timeout=30)
        if response.ok:
            print("WhatsApp notification sent via Twilio.")
        else:
            print(f"WhatsApp send failed via Twilio: {response.status_code} {response.text}")
        return

    api_url = os.getenv("WHATSAPP_API_URL")
    api_token = os.getenv("WHATSAPP_API_TOKEN")
    if api_url and api_token:
        headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json",
        }
        payload = {
            "to": to_number,
            "message": message,
        }
        if media_base:
            payload["media_url"] = media_base.rstrip("/") + "/" + Path(filename).name
        response = requests.post(api_url, json=payload, headers=headers, timeout=30)
        if response.ok:
            print("WhatsApp notification sent via generic API.")
        else:
            print(f"WhatsApp send failed via generic API: {response.status_code} {response.text}")
        return

    print("WhatsApp service configuration is incomplete; skipping WhatsApp notification.")


if __name__ == "__main__":
    # Execution Logic
    if not should_send_report():
        print("Skipping report generation. Scheduled for Fridays at 11:00 and on the 1st of each month at 11:00 unless FORCE_SEND=1.")
        sys.exit(0)
    df_bio = get_biometric_data()
    df_users = get_erp_users()
    df_remote = get_remote_checkin_data()

    if not df_remote.empty:
        df_bio = pd.concat([df_bio, df_remote], ignore_index=True)

    df_bio['user_id'] = df_bio['user_id'].astype(str)
    df_users['attendance_device_id'] = df_users['attendance_device_id'].astype(str)

    write_id_log(df_bio, df_users, df_remote)

    df_merged = pd.merge(df_bio, df_users, left_on='user_id', right_on='attendance_device_id')
    df_merged['date'] = df_merged['timestamp'].dt.date
    df_merged['time'] = df_merged['timestamp'].dt.time

    # Calculate hours worked per employee
    def calculate_hours(group):
        total_hours = 0
        for date_val in group['date'].unique():
            day_data = group[group['date'] == date_val].sort_values('timestamp')
            if len(day_data) >= 2:
                if datetime(2026, 2, 18).date() <= date_val <= datetime(2026, 3, 19).date():
                    shift_start = datetime.strptime('10:00', '%H:%M').time()
                    shift_end = datetime.strptime('16:00', '%H:%M').time()
                else:
                    shift_start = datetime.strptime('09:00', '%H:%M').time()
                    shift_end = datetime.strptime('18:00', '%H:%M').time()

                first_punch = day_data.iloc[0]['timestamp']
                last_punch = day_data.iloc[-1]['timestamp']
                shift_start_dt = datetime.combine(date_val, shift_start)
                shift_end_dt = datetime.combine(date_val, shift_end)

                actual_start = max(first_punch, shift_start_dt)
                actual_end = min(last_punch, shift_end_dt)
                duration = max(0, (actual_end - actual_start).total_seconds() / 3600)
                expected_hours = 6 if shift_end == datetime.strptime('16:00', '%H:%M').time() else 9
                total_hours += min(duration, expected_hours)
        return total_hours

    df_summary = df_merged.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')

    df_user_info = df_users[['attendance_device_id', 'employee_name', 'department', 'designation']].drop_duplicates(subset=['attendance_device_id'])

    employee_order = ['1', '2', '3', '4', '5', '6', '11']
    display_name_map = {
        '1': 'Chauhdry Muhammad Aslam',
        '2': 'Ahmad Hassan Marjan',
        '3': 'Syed Suleman Haider',
        '4': 'Muhammad Basheer',
        '5': 'Khalil Ahmad Yaqoob',
        '6': 'Muhammad Zafar Haji',
        '11': 'Muhammad Atif Zafar'
    }

    df_template = pd.DataFrame({'attendance_device_id': employee_order})
    df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
        df_summary, on='attendance_device_id', how='left')

    df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
    df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
    df_summary['department'] = df_summary['department'].fillna('N/A')
    df_summary['designation'] = df_summary['designation'].fillna('N/A')
    df_summary['serial_no'] = df_summary.index + 1

    # Expected hours: 216 per month
    df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

    # Calculate previous month
    now = datetime.now()
    if now.month == 1:
        prev_month = 12
        prev_year = now.year - 1
    else:
        prev_month = now.month - 1
        prev_year = now.year
    
    month_name = f"{calendar.month_name[prev_month]} {prev_year}"
    months = [(month_name, prev_month, prev_year)]

    for month_name, month_num, year in months:
        month_start = datetime(year, month_num, 1)
        month_end = datetime(year, month_num, calendar.monthrange(year, month_num)[1], 23, 59, 59)
        df_month = df_merged[(df_merged['timestamp'] >= month_start) & (df_merged['timestamp'] <= month_end)].copy()

        df_month_summary = df_month.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')
        df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
            df_month_summary, on='attendance_device_id', how='left')

        df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
        df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
        df_summary['department'] = df_summary['department'].fillna('N/A')
        df_summary['designation'] = df_summary['designation'].fillna('N/A')
        df_summary['serial_no'] = df_summary.index + 1
        df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

        output_folder = os.getenv("OUTPUT_DIR", "reports")
        output_folder_path = Path(output_folder)
        output_folder_path.mkdir(parents=True, exist_ok=True)
        output_name = f"attendance_report_{month_name.replace(' ', '_')}.pdf"
        pdf_path = str(output_folder_path / output_name)
        create_pdf(df_summary, pdf_path, month_name, df_month)
        send_email(pdf_path, month_name)
        send_whatsapp(pdf_path, month_name)