import sqlite3
import pandas as pd
from zk import ZK
import requests
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import calendar
from datetime import datetime, timedelta
import os
import json
import sys
import argparse
from pathlib import Path
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import io
import tempfile

BASE_DIR = Path(__file__).resolve().parent
LOG_DB_PATH = BASE_DIR / "logs" / "attendance_logs.db"
LOG_TEXT_PATH = BASE_DIR / "logs" / "daily_checkin_details.txt"

# Load variables from .env
load_dotenv(BASE_DIR / ".env")

LOGO_PATH = Path(os.getenv("LOGO_PATH", str(BASE_DIR / "company_logo.png")))
if not LOGO_PATH.is_absolute():
    LOGO_PATH = (BASE_DIR / LOGO_PATH).resolve()

BIOMETRIC_IP = os.getenv("BIOMETRIC_IP", "192.168.8.4")
BIOMETRIC_PORT = int(os.getenv("BIOMETRIC_PORT", "4370"))
ERP_ATTENDANCE_DOCTYPE = os.getenv("ERP_ATTENDANCE_DOCTYPE", "Attendance")
ERP_ATTENDANCE_EMPLOYEE_FIELD = os.getenv("ERP_ATTENDANCE_EMPLOYEE_FIELD", "employee")
ERP_ATTENDANCE_DATE_FIELD = os.getenv("ERP_ATTENDANCE_DATE_FIELD", "attendance_date")
ERP_ATTENDANCE_TIME_FIELD = os.getenv("ERP_ATTENDANCE_TIME_FIELD", "attendance_time")
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", str(BASE_DIR / "reports")))

FOOTER_TEXT = (
    "Office - 5, 1st Floor, Markaz Al-Mahbooba, Prince Abdul Mohsen Bin Aziz Road, "
    "Madinah Munawarah, Kingdom of Saudi Arabia. This report is generated by IICC IT dept. "
    "with AI Attendance Agent bot V 1.0"
)

# Access them like this:
erp_url = os.getenv("ERP_URL")
api_key = os.getenv("ERP_API_KEY")
email_pass = os.getenv("EMAIL_PASS")

def normalize_whatsapp_number(number):
    normalized = str(number or "").strip()
    if not normalized:
        return ""
    if normalized.startswith("whatsapp:"):
        return normalized
    if normalized.startswith("+"):
        return f"whatsapp:{normalized}"
    if normalized.isdigit():
        return f"whatsapp:+{normalized}"
    return normalized


def ensure_log_file_exists():
    log_dir = BASE_DIR / Path(os.getenv("LOG_DIR", "logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / os.getenv("LOG_FILE", "attendance_ids.log")
    if not log_path.exists():
        with log_path.open("w", encoding="utf-8") as f:
            f.write(f"Attendance ID log created: {datetime.now().isoformat()}\n")
    return log_path

ensure_log_file_exists()


def ensure_log_db():
    log_dir = BASE_DIR / Path(os.getenv("LOG_DIR", "logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(LOG_DB_PATH)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS daily_checkin (
            log_date TEXT NOT NULL,
            serial INTEGER NOT NULL,
            employee_name TEXT NOT NULL,
            check_in TEXT,
            check_out TEXT,
            PRIMARY KEY(log_date, serial)
        )
        """
    )
    conn.commit()
    return conn


def save_daily_checkin_rows(report_date, rows):
    with ensure_log_db() as conn:
        log_date = report_date.strftime("%d-%m-%Y")
        conn.execute("DELETE FROM daily_checkin WHERE log_date = ?", (log_date,))
        if rows:
            conn.executemany(
                "INSERT INTO daily_checkin (log_date, serial, employee_name, check_in, check_out) VALUES (?, ?, ?, ?, ?)",
                [(report_date.strftime("%d-%m-%Y"), idx, emp_name, check_in, check_out) for idx, (emp_name, check_in, check_out) in enumerate(rows, start=1)]
            )
        conn.commit()


def write_consolidated_text_log_from_db():
    with ensure_log_db() as conn:
        cursor = conn.execute(
            "SELECT log_date, serial, employee_name, check_in, check_out FROM daily_checkin ORDER BY log_date, serial"
        )
        rows = cursor.fetchall()

    current_date = None
    with LOG_TEXT_PATH.open('w', encoding='utf-8') as log_file:
        col_widths = [10, 50, 15, 15]
        headers = ["Serial No", "Emp. name", "Check-in", "Check-out"]
        header_line = " | ".join(headers[i].ljust(col_widths[i]) for i in range(len(headers)))
        separator_line = "-+-".join('-' * col_widths[i] for i in range(len(headers)))

        for log_date, serial, emp_name, check_in, check_out in rows:
            if log_date != current_date:
                current_date = log_date
                if log_file.tell() > 0:
                    log_file.write("\n")
                log_file.write("===== Daily Check-In/out Detail Log =====\n")
                log_file.write(f"Date: {log_date}\n\n")
                log_file.write(header_line + "\n")
                log_file.write(separator_line + "\n")
            line = (
                str(serial).ljust(col_widths[0]) + " | " +
                emp_name.ljust(col_widths[1]) + " | " +
                (check_in or "").ljust(col_widths[2]) + " | " +
                (check_out or "").ljust(col_widths[3])
            )
            log_file.write(line + "\n")


def parse_month_arg(month_str):
    if not month_str:
        return None
    try:
        if len(month_str) == 7:
            return datetime.strptime(month_str, "%Y-%m")
        return datetime.fromisoformat(month_str)
    except ValueError:
        raise ValueError("--month must be YYYY-MM or YYYY-MM-DD")


def get_month_range(reference_date):
    month_start = datetime(reference_date.year, reference_date.month, 1)
    last_day = calendar.monthrange(reference_date.year, reference_date.month)[1]
    month_end = datetime(reference_date.year, reference_date.month, last_day, 23, 59, 59, 999999)
    return month_start, month_end


def parse_args():
    parser = argparse.ArgumentParser(description="Generate attendance PDF reports.")
    parser.add_argument(
        "--month",
        help="Generate a one-off report for the specified month in YYYY-MM or YYYY-MM-DD format."
    )
    return parser.parse_args()


def should_send_report(now=None):
    if now is None:
        now = datetime.now()
    if os.getenv("FORCE_SEND", "0") == "1":
        return True
    if now.hour != 10:
        return False
    return True


def add_page_header(pdf, month_name, page_title):
    pdf.set_line_width(0.18)
    pdf.set_draw_color(192, 0, 0)
    pdf.set_text_color(192, 0, 0)
    pdf.set_font("Arial", "B", 14)
    pdf.set_y(5)
    if LOGO_PATH.is_file():
        pdf.image(str(LOGO_PATH), x=5, y=5, w=25)
        pdf.set_y(18)
    else:
        pdf.set_y(12)
    pdf.set_x(pdf.l_margin)
    content_width = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.cell(content_width, 6, "Insight International Contracting Company (IICC) www.iicc.sa", ln=1, align='C')
    pdf.set_font("Arial", "B", 12)
    pdf.cell(content_width, 6, page_title, ln=1, align='C')
    pdf.set_font("Arial", "", 10)
    pdf.cell(content_width, 5, f"Month: {month_name}", ln=1, align='C')
    pdf.cell(content_width, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  |  Page {pdf.page_no()}", ln=1, align='C')
    pdf.ln(3)


def add_page_footer(pdf):
    pdf.set_line_width(0.18)
    pdf.set_draw_color(192, 0, 0)
    footer_y = pdf.h - 24
    pdf.line(0, footer_y, pdf.w, footer_y)
    pdf.set_xy(10, footer_y + 2)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(192, 0, 0)
    pdf.multi_cell(pdf.w - 20, 4, FOOTER_TEXT, 0, 'C')
    pdf.set_text_color(0, 0, 0)

# 1. Fetch Biometric Data
def get_biometric_data(start_date=None, end_date=None):
    # Fetch biometric attendance records for a month range
    if start_date is None or end_date is None:
        now = datetime.now()
        start_date = datetime(now.year, now.month, 1)
        end_date = now.replace(hour=23, minute=59, second=59, microsecond=999999)

    zk = ZK(BIOMETRIC_IP, port=BIOMETRIC_PORT, timeout=5)
    conn = zk.connect()
    attendance = conn.get_attendance()
    filtered_attendance = [
        {'user_id': str(record.user_id), 'timestamp': record.timestamp}
        for record in attendance
        if start_date <= record.timestamp <= end_date
    ]
    df_biometric = pd.DataFrame(filtered_attendance)
    conn.disconnect()
    return df_biometric

# 2. Fetch ERP User Info
def get_erp_users():
    url = erp_url + '/api/resource/Employee'
    headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}'}
    params = {
        'fields': '["employee_name", "attendance_device_id", "department", "designation"]',
        'limit_page_length': 1000
    }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()['data']
        return pd.DataFrame(data)
    else:
        raise Exception(f"ERP API Error: {response.status_code} - {response.text}")


def get_erp_attendance_data(start_date=None, end_date=None):
    if start_date is None or end_date is None:
        now = datetime.now()
        start_date = datetime(now.year, now.month, 1)
        end_date = now.replace(hour=23, minute=59, second=59, microsecond=999999)

    url = f"{erp_url}/api/resource/{ERP_ATTENDANCE_DOCTYPE}"
    headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}', 'Content-Type': 'application/json'}
    filters = [
        [ERP_ATTENDANCE_DOCTYPE, ERP_ATTENDANCE_DATE_FIELD, ">=", start_date.strftime('%Y-%m-%d')],
        [ERP_ATTENDANCE_DOCTYPE, ERP_ATTENDANCE_DATE_FIELD, "<=", end_date.strftime('%Y-%m-%d')],
    ]
    params = {
        'fields': json.dumps([ERP_ATTENDANCE_EMPLOYEE_FIELD, ERP_ATTENDANCE_DATE_FIELD, ERP_ATTENDANCE_TIME_FIELD]),
        'filters': json.dumps(filters),
        'limit_page_length': 1000,
    }
    response = requests.get(url, headers=headers, params=params, timeout=30)
    if response.status_code == 417:
        # Some ERP installations block query access to the attendance_time field.
        fallback_params = params.copy()
        fallback_fields = [ERP_ATTENDANCE_EMPLOYEE_FIELD, ERP_ATTENDANCE_DATE_FIELD]
        fallback_params['fields'] = json.dumps(fallback_fields)
        response = requests.get(url, headers=headers, params=fallback_params, timeout=30)
    response.raise_for_status()
    data = response.json().get('data', [])

    attendance_records = []
    for item in data:
        employee = item.get(ERP_ATTENDANCE_EMPLOYEE_FIELD)
        date_value = item.get(ERP_ATTENDANCE_DATE_FIELD)
        time_value = item.get(ERP_ATTENDANCE_TIME_FIELD)

        if not employee or not date_value:
            continue

        timestamp_str = f"{date_value}T{time_value or '00:00:00'}"
        try:
            timestamp = datetime.fromisoformat(timestamp_str)
        except ValueError:
            try:
                timestamp = datetime.strptime(timestamp_str, '%Y-%m-%dT%H:%M:%S')
            except ValueError:
                continue

        attendance_records.append({'user_id': str(employee), 'timestamp': timestamp})

    return pd.DataFrame(attendance_records)


def push_checkin_to_erp(record):
    if not erp_url or not api_key:
        return False

    attendance_url = f"{erp_url}/api/resource/{ERP_ATTENDANCE_DOCTYPE}"
    headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}', 'Content-Type': 'application/json'}
    timestamp = record.get('timestamp')
    if isinstance(timestamp, datetime):
        timestamp = timestamp.isoformat()

    date_part = timestamp.split('T')[0] if timestamp and 'T' in timestamp else datetime.now().strftime('%Y-%m-%d')
    time_part = timestamp.split('T')[1] if timestamp and 'T' in timestamp else datetime.now().strftime('%H:%M:%S')
    time_part = time_part[:8]

    payload = {
        ERP_ATTENDANCE_EMPLOYEE_FIELD: record.get('user_id'),
        ERP_ATTENDANCE_DATE_FIELD: date_part,
        ERP_ATTENDANCE_TIME_FIELD: time_part,
        'status': 'Present',
        'remarks': f"Check-in synced from biometric/portal at {timestamp}",
    }

    try:
        response = requests.post(attendance_url, headers=headers, json=payload, timeout=30)
        if response.ok:
            return True
        print(f"ERP check-in push failed: {response.status_code} {response.text}")
    except Exception as exc:
        print(f"ERP check-in push error: {exc}")
    return False


def sync_biometric_data_to_erp(df_bio):
    if df_bio.empty:
        return
    for _, row in df_bio.iterrows():
        push_checkin_to_erp({'user_id': str(row['user_id']), 'timestamp': row['timestamp']})


def get_remote_checkin_data(start_date=None, end_date=None):
    remote_source = os.getenv("REMOTE_CHECKIN_SOURCE")
    if not remote_source:
        return pd.DataFrame(columns=['user_id', 'timestamp'])

    try:
        if remote_source.lower().startswith("http"):
            headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}' }
            response = requests.get(remote_source, headers=headers, timeout=10)
            response.raise_for_status()
            payload = response.json()
            data = payload.get('data', payload) if isinstance(payload, dict) else payload
            df = pd.DataFrame(data)
        elif remote_source.lower().endswith('.csv'):
            df = pd.read_csv(remote_source)
        elif remote_source.lower().endswith('.json'):
            df = pd.read_json(remote_source)
        else:
            raise ValueError("Unsupported REMOTE_CHECKIN_SOURCE format. Use HTTP, CSV, or JSON.")

        user_field = os.getenv('REMOTE_CHECKIN_USER_FIELD')
        if user_field and user_field in df.columns:
            df = df.rename(columns={user_field: 'user_id'})
        elif 'attendance_device_id' in df.columns:
            df = df.rename(columns={'attendance_device_id': 'user_id'})
        elif 'employee_id' in df.columns:
            df = df.rename(columns={'employee_id': 'user_id'})

        if 'timestamp' not in df.columns:
            raise ValueError("Remote checkin source must include a 'timestamp' column")

        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        df = df.dropna(subset=['user_id', 'timestamp'])
        if start_date is not None and end_date is not None:
            df = df[(df['timestamp'] >= start_date) & (df['timestamp'] <= end_date)]
        df['user_id'] = df['user_id'].astype(str)
        return df[['user_id', 'timestamp']]
    except Exception as exc:
        print(f"Warning: failed to load remote checkins from {remote_source}: {exc}")
        return pd.DataFrame(columns=['user_id', 'timestamp'])


def write_id_log(df_bio, df_users, df_remote):
    log_dir = BASE_DIR / Path(os.getenv("LOG_DIR", "logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / os.getenv("LOG_FILE", "attendance_ids.log")

    bio_ids = sorted(set(df_bio['user_id'].astype(str).unique()))
    # Filter out NaN values and convert to string
    erp_ids = sorted(set(str(id) for id in df_users['attendance_device_id'].dropna().unique()))
    remote_ids = sorted(set(df_remote['user_id'].astype(str).unique())) if not df_remote.empty else []

    matched_ids = sorted(set(bio_ids).intersection(erp_ids))
    biometric_only = sorted(set(bio_ids) - set(erp_ids))
    erp_only = sorted(set(erp_ids) - set(bio_ids))

    with open(log_path, 'a', encoding='utf-8') as log_file:
        log_file.write(f"\n===== Attendance ID Log: {datetime.now().isoformat()} =====\n")
        log_file.write(f"Biometric IDs ({len(bio_ids)}): {bio_ids}\n")
        log_file.write(f"ERP IDs ({len(erp_ids)}): {erp_ids}\n")
        if remote_ids:
            log_file.write(f"Remote check-in IDs ({len(remote_ids)}): {remote_ids}\n")
            remote_matched = sorted(set(remote_ids).intersection(erp_ids))
            remote_only = sorted(set(remote_ids) - set(erp_ids))
            log_file.write(f"Remote matched ERP IDs ({len(remote_matched)}): {remote_matched}\n")
            log_file.write(f"Remote-only IDs ({len(remote_only)}): {remote_only}\n")

        log_file.write(f"Matched IDs ({len(matched_ids)}): {matched_ids}\n")
        log_file.write(f"Biometric-only IDs ({len(biometric_only)}): {biometric_only}\n")
        log_file.write(f"ERP-only IDs ({len(erp_only)}): {erp_only}\n")
        log_file.write("====================================================\n")

    print(f"Attendance ID log written to: {log_path}")


def format_duration(start, end):
    if not isinstance(start, datetime) or not isinstance(end, datetime):
        return "N/A"
    duration = end - start
    if duration.total_seconds() < 0:
        return "N/A"
    hours = int(duration.total_seconds() // 3600)
    minutes = int((duration.total_seconds() % 3600) // 60)
    return f"{hours}h {minutes}m"


def write_daily_checkin_log(df_merged, df_users, report_start, report_end):
    exclude_names = {
        "CHAUHDRY MUHAMMAD ASLAM",
        "AHMAD HASAN MARJAN",
        "AHMED HASAN MARJAN",
        "ALJABRI ABDULELAH MAJED",
    }

    def normalize_name(value):
        return " ".join(str(value or "").upper().split())

    df_users = df_users.copy()
    df_users['attendance_device_id'] = df_users['attendance_device_id'].astype(str)
    df_merged = df_merged.copy()
    df_merged['attendance_device_id'] = df_merged['attendance_device_id'].astype(str)
    df_merged['timestamp'] = pd.to_datetime(df_merged['timestamp'], errors='coerce')
    df_merged = df_merged.dropna(subset=['timestamp'])
    df_merged['date'] = df_merged['timestamp'].dt.date

    rows = []
    for _, user in df_users.sort_values('attendance_device_id').iterrows():
        emp_id = str(user.get('attendance_device_id', '') or '').strip()
        if not emp_id:
            continue
        emp_name = (user.get('employee_name') or user.get('employee') or 'N/A').strip()
        if normalize_name(emp_name) in exclude_names:
            continue

        emp_data = df_merged[df_merged['attendance_device_id'] == emp_id]
        if emp_data.empty:
            rows.append((emp_name, '', ''))
            continue

        for _, group in emp_data.sort_values('timestamp').groupby('date', sort=True):
            times = [ts.strftime('%H:%M:%S') for ts in group['timestamp']]
            check_in = times[0] if times else ''
            check_out = times[-1] if len(times) > 1 else ''
            rows.append((emp_name, check_in, check_out))

    atif_row = None
    for idx, row in enumerate(rows):
        if row[0] == 'MUHAMMAD ATIF ZAFAR':
            atif_row = rows.pop(idx)
            break
    if atif_row is not None:
        insert_index = next((i for i, row in enumerate(rows) if row[0] == 'MUHAMMAD ZAFAR HAJI'), len(rows))
        rows.insert(insert_index + 1, atif_row)

    save_daily_checkin_rows(report_start, rows)
    write_consolidated_text_log_from_db()

    print(f"Daily check-in detail log updated in DB and consolidated file: {LOG_TEXT_PATH}")

# 3. Generate PDF Summary
# 3. Generate PDF Summary
def create_pdf(df_final, filename, month_name, df_merged):
    pdf = FPDF('L', 'mm', 'A4')
    pdf.set_auto_page_break(auto=False, margin=0)
    pdf.add_page()
    add_page_header(pdf, month_name, f"Daily Attendance Summary - {month_name}")

    table_width = 255
    page_width = pdf.w
    left_margin = (page_width - table_width) / 2
    pdf.set_line_width(0.18)
    pdf.set_draw_color(192, 0, 0)

    headers = [
        ("No.", 12),
        ("Employee Name", 64),
        ("Designation", 60),
        ("Department", 60),
        ("Hours", 30),
        ("Pct", 29),
    ]
    row_height = 16
    table_y = pdf.get_y()
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(192, 0, 0)
    pdf.set_draw_color(255, 255, 255)
    pdf.set_text_color(255, 255, 255)
    x = left_margin
    for label, width in headers:
        pdf.set_xy(x, table_y)
        pdf.cell(width, row_height, label, 1, 0, 'C', fill=True)
        x += width
    pdf.set_draw_color(192, 0, 0)

    pdf.set_y(table_y + row_height)
    pdf.set_font("Arial", "", 9)
    pdf.set_text_color(0, 0, 0)

    for index, row in df_final.iterrows():
        row_y = pdf.get_y()
        if row_y + row_height > pdf.h - 20:
            add_page_footer(pdf)
            pdf.add_page()
            add_page_header(pdf, month_name, f"Monthly Attendance Summary - {month_name}")
            table_y = pdf.get_y()
            pdf.set_font("Arial", "B", 10)
            pdf.set_fill_color(192, 0, 0)
            pdf.set_text_color(255, 255, 255)
            x = left_margin
            for label, width in headers:
                pdf.set_xy(x, table_y)
                pdf.cell(width, row_height, label, 1, 0, 'C', fill=True)
                x += width
            pdf.set_y(table_y + row_height)
            pdf.set_font("Arial", "", 9)
            pdf.set_text_color(0, 0, 0)
            row_y = pdf.get_y()

        x = left_margin
        pdf.set_xy(x, row_y)
        pdf.cell(12, row_height, str(row['serial_no']), 1, 0, 'C')
        x += 12
        pdf.set_xy(x, row_y)
        pdf.cell(64, row_height, str(row['employee_name']), 1, 0)
        x += 64
        pdf.set_xy(x, row_y)
        pdf.cell(60, row_height, str(row['designation']), 1, 0)
        x += 60
        pdf.set_xy(x, row_y)
        pdf.cell(60, row_height, str(row.get('department', 'N/A')), 1, 0)
        x += 60
        pdf.set_xy(x, row_y)
        pdf.cell(30, row_height, f"{row['total_hours']:.1f}", 1, 0, 'C')
        x += 30

        pct_val = max(0, min(row['percentage'], 100))
        pct_display = f"{pct_val:.1f}%"
        fig, ax = plt.subplots(figsize=(0.45, 0.45))
        ax.pie([pct_val, 100 - pct_val], colors=['#C00000', '#FFFFFF'], startangle=90, counterclock=False, wedgeprops={'linewidth': 0})
        ax.axis('equal')
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as temp_img:
            fig.savefig(temp_img.name, format='png', transparent=True, bbox_inches='tight')
        plt.close(fig)
        image_y = row_y + 3
        pdf.image(temp_img.name, x=x + 8, y=image_y, w=9, type='PNG')
        try:
            os.remove(temp_img.name)
        except OSError:
            pass

        pdf.set_xy(x, row_y)
        pdf.cell(29, row_height, pct_display, 1, 0, 'C')
        pdf.set_y(row_y + row_height)

    add_page_footer(pdf)
    add_timesheet_pages(pdf, df_final, df_merged, month_name)
    pdf.output(filename)

def add_timesheet_pages(pdf, df_final, df_merged, month_name):
    for index, row in df_final.iterrows():
        emp_name = row['employee_name']
        emp_device_id = str(row.get('attendance_device_id', ''))
        
        emp_data = df_merged[df_merged['attendance_device_id'] == emp_device_id].copy()
        if emp_data.empty:
            continue
        
        emp_data['date'] = emp_data['timestamp'].dt.date
        emp_data['time'] = emp_data['timestamp'].dt.strftime('%H:%M:%S')
        emp_data = emp_data.sort_values('timestamp')
        
        def draw_timesheet_header():
            pdf.set_font("Arial", "B", 9)
            pdf.set_fill_color(192, 0, 0)
            pdf.set_draw_color(255, 255, 255)
            pdf.set_text_color(255, 255, 255)
            pdf.set_x(left_margin)
            pdf.cell(15, 8, "S.No", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Date", 1, 0, 'C', fill=True)
            pdf.cell(25, 8, "Day", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Check-In", 1, 0, 'C', fill=True)
            pdf.cell(30, 8, "Check-Out", 1, 0, 'C', fill=True)
            pdf.cell(25, 8, "Duration", 1, 1, 'C', fill=True)
            pdf.set_draw_color(192, 0, 0)
            pdf.set_font("Arial", "", 8)
            pdf.set_text_color(0, 0, 0)

        pdf.add_page('P')
        add_page_header(pdf, month_name, f"Attendance Timesheet - {emp_name}")
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 6, f"Designation: {row.get('designation', 'N/A')} | Department: {row.get('department', 'N/A')}", ln=1, align='C')
        pdf.ln(4)

        table_width = 155
        page_width = pdf.w
        left_margin = (page_width - table_width) / 2
        pdf.set_x(left_margin)
        pdf.set_line_width(0.18)

        draw_timesheet_header()

        try:
            month_num = datetime.strptime(month_name.split()[0], '%B').month
            year = int(month_name.split()[1])
        except Exception:
            month_num = 1
            year = 2026
        month_start = datetime(year, month_num, 1).date()
        month_end = datetime(year, month_num, calendar.monthrange(year, month_num)[1]).date()
        all_dates = [month_start + timedelta(days=i) for i in range((month_end - month_start).days + 1)]
        
        serial_no = 1
        total_days = 0
        total_hours = 0
        for date_val in all_dates:
            if pdf.get_y() + 12 > pdf.h - 20:
                add_page_footer(pdf)
                pdf.add_page('P')
                add_page_header(pdf, month_name, f"Attendance Timesheet - {emp_name}")
                pdf.set_font("Arial", "", 10)
                pdf.cell(0, 6, f"Designation: {row.get('designation', 'N/A')} | Department: {row.get('department', 'N/A')}", ln=1, align='C')
                pdf.ln(4)
                pdf.set_x(left_margin)
                pdf.set_line_width(0.18)
                draw_timesheet_header()

            day_data = emp_data[emp_data['date'] == date_val].sort_values('timestamp')
            day_name = date_val.strftime('%A')
            if len(day_data) >= 2:
                check_in = day_data.iloc[0]['time']
                check_out = day_data.iloc[-1]['time']
                duration_min = (day_data.iloc[-1]['timestamp'] - day_data.iloc[0]['timestamp']).total_seconds() / 60
                duration_hrs = f"{int(duration_min // 60)}:{int(duration_min % 60):02d}"
                total_days += 1
                total_hours += duration_min / 60
            elif len(day_data) == 1:
                check_in = day_data.iloc[0]['time']
                check_out = "N/A"
                duration_hrs = "N/A"
            else:
                check_in = "N/A"
                check_out = "N/A"
                duration_hrs = "N/A"
            
            pdf.set_x(left_margin)
            pdf.cell(15, 6, str(serial_no), 1, 0, 'C')
            pdf.cell(30, 6, str(date_val), 1, 0, 'C')
            pdf.cell(25, 6, day_name[:3], 1, 0, 'C')  # Short day name
            pdf.cell(30, 6, str(check_in), 1, 0, 'C')
            pdf.cell(30, 6, str(check_out), 1, 0, 'C')
            pdf.cell(25, 6, duration_hrs, 1, 1, 'C')
            serial_no += 1
        
        summary = f"Total Days: {total_days}, Total Hours: {total_hours:.1f}"
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 6, summary, 0, 1, 'C')
        add_page_footer(pdf)

# 4. Email Function
def send_email(filename, month_name):
    msg = MIMEMultipart()
    msg['Subject'] = f'Daily Attendance Report - {month_name}'
    msg['From'] = os.getenv("EMAIL_USER")
    msg['To'] = os.getenv("RECIPIENT_EMAIL")
    
    with open(filename, "rb") as f:
        attach = MIMEApplication(f.read(), _subtype="txt")
        attach.add_header('Content-Disposition', 'attachment', filename=Path(filename).name)
        msg.attach(attach)
    
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = int(os.getenv("SMTP_PORT"))
    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_USER"), email_pass)
        server.send_message(msg)


def send_whatsapp(filename, month_name, to_numbers=None, from_number=None):
    if isinstance(to_numbers, str):
        to_numbers = [item.strip() for item in to_numbers.replace(";", ",").split(",") if item.strip()]
    elif to_numbers is None:
        candidates = os.getenv("WHATSAPP_TO_NUMBER") or os.getenv("WHATSAPP_TO_NUMBERS")
        to_numbers = [item.strip() for item in str(candidates or "").replace(";", ",").split(",") if item.strip()]

    if not to_numbers:
        print("WhatsApp recipient numbers are not configured; skipping WhatsApp notification.")
        return

    from_number = from_number or os.getenv("WHATSAPP_FROM_NUMBER")
    if not from_number:
        print("WhatsApp from number is not configured; skipping WhatsApp notification.")
        return

    from_number = normalize_whatsapp_number(from_number)
    to_numbers = [normalize_whatsapp_number(number) for number in to_numbers if normalize_whatsapp_number(number)]
    if not to_numbers:
        print("No valid WhatsApp recipient numbers were provided; skipping WhatsApp notification.")
        return

    message_template = os.getenv(
        "WHATSAPP_MESSAGE_TEMPLATE",
        f"Daily check-in log for {month_name} is ready. File: {Path(filename).name}"
    )
    message = message_template.replace("{month_name}", month_name).replace("{filename}", Path(filename).name)

    twilio_sid = os.getenv("TWILIO_ACCOUNT_SID")
    twilio_token = os.getenv("TWILIO_AUTH_TOKEN")
    media_base = os.getenv("WHATSAPP_MEDIA_URL_BASE")

    if twilio_sid and twilio_token:
        url = f"https://api.twilio.com/2010-04-01/Accounts/{twilio_sid}/Messages.json"
        for recipient in to_numbers:
            data = {
                "From": from_number,
                "To": recipient,
                "Body": message,
            }
            if media_base:
                data["MediaUrl"] = media_base.rstrip("/") + "/" + Path(filename).name
            response = requests.post(url, data=data, auth=(twilio_sid, twilio_token), timeout=30)
            if response.ok:
                print(f"WhatsApp notification sent to {recipient} via Twilio.")
            else:
                print(f"WhatsApp send failed for {recipient} via Twilio: {response.status_code} {response.text}")
        return

    api_url = os.getenv("WHATSAPP_API_URL")
    api_token = os.getenv("WHATSAPP_API_TOKEN")
    if api_url and api_token:
        headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json",
        }
        for recipient in to_numbers:
            payload = {
                "to": recipient,
                "message": message,
            }
            if media_base:
                payload["media_url"] = media_base.rstrip("/") + "/" + Path(filename).name
            response = requests.post(api_url, json=payload, headers=headers, timeout=30)
            if response.ok:
                print(f"WhatsApp notification sent to {recipient} via generic API.")
            else:
                print(f"WhatsApp send failed for {recipient} via generic API: {response.status_code} {response.text}")
        return

    print("WhatsApp service configuration is incomplete; skipping WhatsApp notification.")


if __name__ == "__main__":
    # Execution Logic
    args = parse_args()
    ensure_log_file_exists()
    report_date = parse_month_arg(args.month) if args.month else None

    if report_date is None:
        if not should_send_report():
            print("Skipping report generation. Scheduled for daily 10:00 AM unless FORCE_SEND=1.")
            sys.exit(0)
        report_date = datetime.now()
    else:
        print(f"Generating one-off attendance report for {report_date.strftime('%B %Y')}.")

    report_start, report_end = get_month_range(report_date)
    month_name = f"{calendar.month_name[report_date.month]} {report_date.year}"

    df_erp_attendance = get_erp_attendance_data(report_start, report_end)
    df_bio = get_biometric_data(report_start, report_end)
    df_users = get_erp_users()
    df_remote = get_remote_checkin_data(report_start, report_end)

    if os.getenv("SYNC_BIOMETRIC_TO_ERP", "0") == "1":
        sync_biometric_data_to_erp(df_bio)

    attendance_frames = []
    for frame in (df_erp_attendance, df_bio, df_remote):
        if not frame.empty:
            attendance_frames.append(frame)

    df_attendance = pd.concat(attendance_frames, ignore_index=True) if attendance_frames else pd.DataFrame(columns=['user_id', 'timestamp'])
    df_attendance = df_attendance.drop_duplicates(subset=['user_id', 'timestamp'])
    df_attendance['user_id'] = df_attendance['user_id'].astype(str)
    df_users['attendance_device_id'] = df_users['attendance_device_id'].astype(str)

    write_id_log(df_attendance, df_users, df_remote)

    df_merged = pd.merge(df_attendance, df_users, left_on='user_id', right_on='attendance_device_id')
    df_merged['date'] = df_merged['timestamp'].dt.date
    df_merged['time'] = df_merged['timestamp'].dt.time

    write_daily_checkin_log(df_merged, df_users, report_start, report_end)

    # Calculate hours worked per employee
    def calculate_hours(group):
        total_hours = 0
        for date_val in group['date'].unique():
            day_data = group[group['date'] == date_val].sort_values('timestamp')
            if len(day_data) >= 2:
                if datetime(2026, 2, 18).date() <= date_val <= datetime(2026, 3, 19).date():
                    shift_start = datetime.strptime('10:00', '%H:%M').time()
                    shift_end = datetime.strptime('16:00', '%H:%M').time()
                else:
                    shift_start = datetime.strptime('09:00', '%H:%M').time()
                    shift_end = datetime.strptime('18:00', '%H:%M').time()

                first_punch = day_data.iloc[0]['timestamp']
                last_punch = day_data.iloc[-1]['timestamp']
                shift_start_dt = datetime.combine(date_val, shift_start)
                shift_end_dt = datetime.combine(date_val, shift_end)

                actual_start = max(first_punch, shift_start_dt)
                actual_end = min(last_punch, shift_end_dt)
                duration = max(0, (actual_end - actual_start).total_seconds() / 3600)
                expected_hours = 6 if shift_end == datetime.strptime('16:00', '%H:%M').time() else 9
                total_hours += min(duration, expected_hours)
        return total_hours

    df_summary = df_merged.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')

    df_user_info = df_users[['attendance_device_id', 'employee_name', 'department', 'designation']].drop_duplicates(subset=['attendance_device_id'])

    employee_order = ['1', '2', '3', '4', '5', '6', '11']
    display_name_map = {
        '1': 'Chauhdry Muhammad Aslam',
        '2': 'Ahmad Hassan Marjan',
        '3': 'Syed Suleman Haider',
        '4': 'Muhammad Basheer',
        '5': 'Khalil Ahmad Yaqoob',
        '6': 'Muhammad Zafar Haji',
        '11': 'Muhammad Atif Zafar'
    }

    df_template = pd.DataFrame({'attendance_device_id': employee_order})
    df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
        df_summary, on='attendance_device_id', how='left')

    df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
    df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
    df_summary['department'] = df_summary['department'].fillna('N/A')
    df_summary['designation'] = df_summary['designation'].fillna('N/A')
    df_summary['serial_no'] = df_summary.index + 1

    # Expected hours: 216 per month
    df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

    now = datetime.now()
    df_month = df_merged[(df_merged['timestamp'] >= report_start) & (df_merged['timestamp'] <= report_end)].copy()

    df_month_summary = df_month.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')
    df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
        df_month_summary, on='attendance_device_id', how='left')

    df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
    df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
    df_summary['department'] = df_summary['department'].fillna('N/A')
    df_summary['designation'] = df_summary['designation'].fillna('N/A')
    df_summary['serial_no'] = df_summary.index + 1
    df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_name = f"attendance_report_{now.strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf_path = str(OUTPUT_DIR / output_name)
    create_pdf(df_summary, pdf_path, month_name, df_month)
    send_email(pdf_path, month_name)
    send_whatsapp(pdf_path, month_name)