import pandas as pd
from zk import ZK
import requests
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import calendar
from datetime import datetime, timedelta
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent
# Load variables from .env
load_dotenv(BASE_DIR / ".env")

# Access them like this:
erp_url = os.getenv("ERP_URL")
api_key = os.getenv("ERP_API_KEY")
email_pass = os.getenv("EMAIL_PASS")

print(f"Connecting to ERP at: {erp_url}")

# 1. Fetch Biometric Data
def get_biometric_data():
    zk = ZK('192.168.8.4', port=4370, timeout=5)
    conn = zk.connect()
    attendance = conn.get_attendance()
    # Filter for Jan-Mar 2026
    start_date = datetime(2026, 1, 1)
    end_date = datetime(2026, 3, 31, 23, 59, 59)
    filtered_attendance = [{'user_id': record.user_id, 'timestamp': record.timestamp} for record in attendance if start_date <= record.timestamp <= end_date]
    df_biometric = pd.DataFrame(filtered_attendance)
    conn.disconnect()
    return df_biometric

# 2. Fetch ERP User Info
def get_erp_users():
    url = erp_url + '/api/resource/Employee'
    headers = {'Authorization': f'token {api_key}:{os.getenv("ERP_API_SECRET")}'}
    params = {
        'fields': '["employee_name", "attendance_device_id", "department", "designation"]',
        'limit_page_length': 1000
    }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()['data']
        return pd.DataFrame(data)
    else:
        raise Exception(f"ERP API Error: {response.status_code} - {response.text}")

# 3. Generate PDF Summary
# 3. Generate PDF Summary
def create_pdf(df_final, filename, month_name, df_merged):
    pdf = FPDF('L', 'mm', 'A4')
    pdf.set_auto_page_break(auto=False, margin=0)
    pdf.add_page()

    logo_path = os.getenv("LOGO_PATH", str(Path(__file__).resolve().parent / "company_logo.png"))
    if os.path.isfile(logo_path):
        pdf.image(logo_path, x=10, y=8, w=25)

    pdf.set_xy(0, 8)
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 7, "Insight International Contracting Company", ln=1, align='C')
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 6, f"Monthly Attendance Summary - {month_name}", ln=1, align='C')
    pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=1, align='C')
    pdf.ln(3)

    table_width = 230
    page_width = pdf.w
    left_margin = (page_width - table_width) / 2
    pdf.set_y(70)  # Lower the table further to avoid overlap
    pdf.set_x(left_margin)
    pdf.set_line_width(0.5)

    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(192, 0, 0)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(10, 12, "No.", 1, 0, 'C', fill=True)
    pdf.cell(60, 12, "Employee Name", 1, 0, 'C', fill=True)
    pdf.cell(55, 12, "Designation", 1, 0, 'C', fill=True)
    pdf.cell(55, 12, "Department", 1, 0, 'C', fill=True)
    pdf.cell(25, 12, "Hours", 1, 0, 'C', fill=True)
    pdf.cell(25, 12, "Pct", 1, 0, 'C', fill=True)
    pdf.ln()

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 9)
    for index, row in df_final.iterrows():
        pdf.set_x(left_margin)
        pdf.cell(10, 12, str(row['serial_no']), 1, 0, 'C')
        pdf.cell(60, 12, str(row['employee_name']), 1, 0)
        pdf.cell(55, 12, str(row['designation']), 1, 0)
        pdf.cell(55, 12, str(row.get('department', 'N/A')), 1, 0)
        pdf.cell(25, 12, f"{row['total_hours']:.1f}", 1, 0, 'C')

        pct_val = row['percentage']
        pct_display = f"{pct_val:.1f}%"
        pdf.set_fill_color(192, 0, 0)
        pdf.set_text_color(255, 255, 255)
        # Draw vertical bar
        bar_height = (pct_val / 100) * 10
        pdf.rect(pdf.get_x() + 10, pdf.get_y() + 12 - bar_height, 5, bar_height, 'F')
        pdf.set_xy(pdf.get_x(), pdf.get_y())
        pdf.cell(25, 12, pct_display, 1, 0, 'C')
        pdf.set_text_color(0, 0, 0)
        pdf.ln()

    pdf.set_y(193)
    pdf.set_draw_color(192, 0, 0)
    pdf.set_line_width(1)
    pdf.line(0, 193, pdf.w, 193)
    pdf.set_y(195)
    pdf.set_text_color(192, 0, 0)
    pdf.set_font("Arial", "I", 9)
    footer_text = "Office - 5, 1st Floor, Markaz Al-Mahbooba, Prince Abdul Mohsen Bin Aziz Road, Madinah Munawarah, Kingdom of Saudi Arabia. This report is generated by IICC IT dept. with AI Attendance Agent bot V 1.0"
    pdf.set_x(0)
    pdf.multi_cell(0, 4, footer_text, 0, 'C')

    add_timesheet_pages(pdf, df_final, df_merged, month_name)
    pdf.output(filename)

def add_timesheet_pages(pdf, df_final, df_merged, month_name):
    for index, row in df_final.iterrows():
        emp_name = row['employee_name']
        emp_device_id = str(row.get('attendance_device_id', ''))
        
        emp_data = df_merged[df_merged['attendance_device_id'] == emp_device_id].copy()
        if emp_data.empty:
            continue
        
        emp_data['date'] = emp_data['timestamp'].dt.date
        emp_data['time'] = emp_data['timestamp'].dt.strftime('%H:%M:%S')
        emp_data = emp_data.sort_values('timestamp')
        
        pdf.add_page('P')
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, f"Attendance Timesheet - {emp_name}", ln=1, align='C')
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 6, f"Month: {month_name}", ln=1, align='C')
        pdf.cell(0, 6, f"Designation: {row.get('designation', 'N/A')} | Department: {row.get('department', 'N/A')}", ln=1, align='C')
        pdf.ln(5)

        table_width = 155
        page_width = pdf.w
        left_margin = (page_width - table_width) / 2
        pdf.set_x(left_margin)
        
        pdf.set_line_width(0.5)
        pdf.set_font("Arial", "B", 9)
        pdf.set_fill_color(192, 0, 0)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(15, 8, "S.No", 1, 0, 'C', fill=True)
        pdf.cell(30, 8, "Date", 1, 0, 'C', fill=True)
        pdf.cell(25, 8, "Day", 1, 0, 'C', fill=True)
        pdf.cell(30, 8, "Check-In", 1, 0, 'C', fill=True)
        pdf.cell(30, 8, "Check-Out", 1, 0, 'C', fill=True)
        pdf.cell(25, 8, "Duration", 1, 1, 'C', fill=True)
        
        pdf.set_font("Arial", "", 8)
        pdf.set_text_color(0, 0, 0)
        
        daily_records = emp_data.groupby('date').apply(lambda x: x.sort_values('timestamp')).reset_index(drop=True)
        
        serial_no = 1
        total_days = 0
        total_hours = 0
        for date_val in sorted(emp_data['date'].unique()):
            day_data = emp_data[emp_data['date'] == date_val].sort_values('timestamp')
            day_name = date_val.strftime('%A')
            if len(day_data) >= 2:
                check_in = day_data.iloc[0]['time']
                check_out = day_data.iloc[-1]['time']
                duration_min = (day_data.iloc[-1]['timestamp'] - day_data.iloc[0]['timestamp']).total_seconds() / 60
                duration_hrs = f"{int(duration_min // 60)}:{int(duration_min % 60):02d}"
                total_days += 1
                total_hours += duration_min / 60
            else:
                check_in = day_data.iloc[0]['time'] if len(day_data) > 0 else "N/A"
                check_out = "N/A"
                duration_hrs = "N/A"
            
            pdf.set_x(left_margin)
            pdf.cell(15, 6, str(serial_no), 1, 0, 'C')
            pdf.cell(30, 6, str(date_val), 1, 0, 'C')
            pdf.cell(25, 6, day_name[:3], 1, 0, 'C')  # Short day name
            pdf.cell(30, 6, check_in, 1, 0, 'C')
            pdf.cell(30, 6, check_out, 1, 0, 'C')
            pdf.cell(25, 6, duration_hrs, 1, 1, 'C')
            serial_no += 1
        
        # Summary
        summary = f"Total Days: {total_days}, Total Hours: {total_hours:.1f}"
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 6, summary, 0, 1, 'C')

# 4. Email Function
def send_email(filename, month_name):
    msg = MIMEMultipart()
    msg['Subject'] = f'Monthly Attendance Report - {month_name}'
    msg['From'] = os.getenv("EMAIL_USER")
    msg['To'] = os.getenv("RECIPIENT_EMAIL")
    
    with open(filename, "rb") as f:
        attach = MIMEApplication(f.read(), _subtype="pdf")
        attach.add_header('Content-Disposition', 'attachment', filename=Path(filename).name)
        msg.attach(attach)
    
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = int(os.getenv("SMTP_PORT"))
    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_USER"), email_pass)
        server.send_message(msg)

if __name__ == "__main__":
    # Execution Logic
    df_bio = get_biometric_data()
    df_users = get_erp_users()
    df_bio['user_id'] = df_bio['user_id'].astype(str)
    df_users['attendance_device_id'] = df_users['attendance_device_id'].astype(str)

    df_merged = pd.merge(df_bio, df_users, left_on='user_id', right_on='attendance_device_id')
    df_merged['date'] = df_merged['timestamp'].dt.date
    df_merged['time'] = df_merged['timestamp'].dt.time

    # Calculate hours worked per employee
    def calculate_hours(group):
        total_hours = 0
        for date_val in group['date'].unique():
            day_data = group[group['date'] == date_val].sort_values('timestamp')
            if len(day_data) >= 2:
                # Determine shift hours
                if datetime(2026, 2, 18).date() <= date_val <= datetime(2026, 3, 19).date():
                    shift_start = datetime.strptime('10:00', '%H:%M').time()
                    shift_end = datetime.strptime('16:00', '%H:%M').time()
                else:
                    shift_start = datetime.strptime('09:00', '%H:%M').time()
                    shift_end = datetime.strptime('18:00', '%H:%M').time()
                
                # Filter punches within shift
                shift_punches = day_data[(day_data['time'] >= shift_start) & (day_data['time'] <= shift_end)]
                if len(shift_punches) >= 2:
                    first_punch = shift_punches.iloc[0]['timestamp']
                    last_punch = shift_punches.iloc[-1]['timestamp']
                    duration = (last_punch - first_punch).total_seconds() / 3600
                    total_hours += min(duration, 9)  # Cap at 9 hours
        return total_hours

    df_summary = df_merged.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')

    df_user_info = df_users[['attendance_device_id', 'employee_name', 'department', 'designation']].drop_duplicates(subset=['attendance_device_id'])

    employee_order = ['1', '2', '3', '4', '5', '6', '11']
    display_name_map = {
        '1': 'Chauhdry Muhammad Aslam',
        '2': 'Ahmad Hassan Marjan',
        '3': 'Syed Suleman Haider',
        '4': 'Muhammad Basheer',
        '5': 'Khalil Ahmad Yaqoob',
        '6': 'Muhammad Zafar Haji',
        '11': 'Muhammad Atif Zafar'
    }

    df_template = pd.DataFrame({'attendance_device_id': employee_order})
    df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
        df_summary, on='attendance_device_id', how='left')

    df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
    df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
    df_summary['department'] = df_summary['department'].fillna('N/A')
    df_summary['designation'] = df_summary['designation'].fillna('N/A')
    df_summary['serial_no'] = df_summary.index + 1

    # Expected hours: 216 per month
    df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

    months = [
        ("January 2026", 1, 2026),
        ("February 2026", 2, 2026),
        ("March 2026", 3, 2026)
    ]

    for month_name, month_num, year in months:
        month_start = datetime(year, month_num, 1)
        month_end = datetime(year, month_num, calendar.monthrange(year, month_num)[1], 23, 59, 59)
        df_month = df_merged[(df_merged['timestamp'] >= month_start) & (df_merged['timestamp'] <= month_end)].copy()

        df_month_summary = df_month.groupby('attendance_device_id').apply(calculate_hours).reset_index(name='total_hours')
        df_summary = df_template.merge(df_user_info, on='attendance_device_id', how='left').merge(
            df_month_summary, on='attendance_device_id', how='left')

        df_summary['total_hours'] = df_summary['total_hours'].fillna(0)
        df_summary['employee_name'] = df_summary['attendance_device_id'].map(display_name_map).fillna(df_summary['employee_name'].fillna('N/A'))
        df_summary['department'] = df_summary['department'].fillna('N/A')
        df_summary['designation'] = df_summary['designation'].fillna('N/A')
        df_summary['serial_no'] = df_summary.index + 1
        df_summary['percentage'] = (df_summary['total_hours'] / 216) * 100

        output_folder = os.getenv("OUTPUT_DIR", "reports")
        output_folder_path = Path(output_folder)
        output_folder_path.mkdir(parents=True, exist_ok=True)
        output_name = f"attendance_report_{month_name.replace(' ', '_')}.pdf"
        pdf_path = str(output_folder_path / output_name)
        create_pdf(df_summary, pdf_path, month_name, df_month)
        send_email(pdf_path, month_name)